#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class PolicyRow:
    method: str
    policy: str
    success_rate: float
    mean_route_completion: float
    mean_cte_m: float
    mean_goal_dist_min_m: float
    n: int


def _format_float_for_path(x: float) -> str:
    if abs(float(x) - round(float(x))) <= 1e-9:
        return f"{float(x):.1f}"
    return str(float(x))


def _safe_float(x: object) -> float:
    try:
        v = float(x)
        return float(v) if math.isfinite(v) else float("nan")
    except Exception:
        return float("nan")


def _safe_int(x: object) -> int:
    try:
        return int(float(x))
    except Exception:
        return 0


def _find_latest_run(parent: Path) -> Path:
    runs = sorted(
        [
            p
            for p in parent.glob("closed_loop_fusion_*")
            if p.is_dir() and p.name.startswith("closed_loop_fusion_")
        ]
    )
    if not runs:
        raise FileNotFoundError(f"No closed_loop_fusion_* runs under: {parent}")
    return runs[-1]


def _read_cfg(run_dir: Path) -> dict:
    p = run_dir / "config.json"
    if not p.exists():
        return {}
    return json.loads(p.read_text(encoding="utf-8"))


def _read_summary_rows(run_dir: Path) -> list[dict]:
    p = run_dir / "summary.csv"
    if not p.exists():
        raise FileNotFoundError(f"Missing summary.csv: {p}")
    with p.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _select_one(rows: list[dict], policy: str) -> dict:
    cand = [r for r in rows if str(r.get("policy", "")) == str(policy)]
    if not cand:
        raise KeyError(
            f"Policy not found in summary.csv: {policy}. "
            f"Available: {sorted({str(r.get('policy', '')) for r in rows})}"
        )
    if len(cand) == 1:
        return cand[0]

    # Prefer max success, then min CTE.
    def key(r: dict) -> tuple[float, float]:
        succ = _safe_float(r.get("success_rate", float("nan")))
        cte = _safe_float(r.get("mean_cte_m", float("nan")))
        succ = succ if math.isfinite(succ) else -1.0
        cte = cte if math.isfinite(cte) else float("inf")
        return (succ, -cte)

    return sorted(cand, key=key, reverse=True)[0]


def _as_row(r: dict, *, method: str, policy: str) -> PolicyRow:
    return PolicyRow(
        method=str(method),
        policy=str(policy),
        success_rate=_safe_float(r.get("success_rate", float("nan"))),
        mean_route_completion=_safe_float(r.get("mean_route_completion", float("nan"))),
        mean_cte_m=_safe_float(r.get("mean_cte_m", float("nan"))),
        mean_goal_dist_min_m=_safe_float(
            r.get("mean_goal_dist_min_m", r.get("mean_goal_dist_final_m", float("nan")))
        ),
        n=_safe_int(r.get("n", 0)),
    )


def _latex_escape(s: str) -> str:
    return (
        str(s)
        .replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
        .replace("#", "\\#")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("$", "\\$")
    )


def _render_latex_table(
    rows: list[PolicyRow], *, delay_s: float, n_tasks: int | None, label: str
) -> str:
    # Keep formatting consistent with IEEE tables + siunitx S columns.
    # Values are fractions in [0,1] for success/completion; meters for CTE/goal.
    caption = (
        "Closed-loop results at VLM delay "
        f"$\\Delta t=\\SI{{{delay_s:g}}}{{s}}$ ("
        + (f"{n_tasks} tasks" if n_tasks is not None else "task windows")
        + "). "
        "Success requires maximum route completion $\\ge 0.95$ and minimum goal distance $\\le "
        "\\SI{3}{m}$."
    )
    out: list[str] = []
    out.append("% Auto-generated by scripts/make_closed_loop_delay_table.py")
    out.append("\\begin{table}[H]")
    out.append("  \\centering")
    out.append(f"  \\caption{{{caption}}}")
    out.append(f"  \\label{{{label}}}")
    out.append("  \\setlength{\\tabcolsep}{6pt}")
    out.append(
        "  \\begin{tabular}{l S[table-format=1.2] S[table-format=1.3] S[table-format=1.3] "
        "S[table-format=1.2]}"
    )
    out.append("    \\toprule")
    out.append(
        "    Method & {Success} & {Completion} & {Mean CTE (m)} & {$d_{\\mathrm{goal,min}}$ (m)} "
        "\\\\"
    )
    out.append("    \\midrule")
    for r in rows:
        out.append(
            "    "
            + _latex_escape(r.method)
            + f" & {r.success_rate:.2f} & {r.mean_route_completion:.3f}"
            + f" & {r.mean_cte_m:.3f} & {r.mean_goal_dist_min_m:.2f} \\\\"
        )
    out.append("    \\bottomrule")
    out.append("  \\end{tabular}")
    out.append("\\end{table}")
    out.append("")
    return "\n".join(out)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate a LaTeX table for a fixed delay from existing step4_main_results "
        "runs."
    )
    p.add_argument(
        "--section5-root",
        type=str,
        default="logs/section5_closed_loop",
        help="Root folder containing step4_main_results/.",
    )
    p.add_argument("--delay-s", type=float, default=2.0, help="Delay (seconds).")
    p.add_argument(
        "--use-stream-fusion",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="If true, use score_fusion_stream/prob_fusion_stream; else use "
        "score_fusion/prob_fusion.",
    )
    p.add_argument(
        "--out-tex",
        type=str,
        default="latex/source_data/closed_loop_delay2_table.tex",
        help="Output .tex path.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    root = Path(args.section5_root).expanduser().resolve()
    delay_tag = _format_float_for_path(float(args.delay_s))

    base = root / "step4_main_results" / f"delay_{delay_tag}"
    if not base.exists():
        raise FileNotFoundError(f"Missing delay folder: {base}")

    run_baselines = _find_latest_run(base / "baselines")
    cfg_base = _read_cfg(run_baselines)
    summary_base = _read_summary_rows(run_baselines)

    # Fusion group selection
    if bool(args.use_stream_fusion):
        score_group = "score_fusion_stream"
        prob_group = "prob_fusion_stream"
        score_policy = "score_fusion_stream"
        prob_policy = "prob_fusion_stream"
        score_method = "Score Fusion"
        prob_method = "Prob Fusion"
    else:
        score_group = "score_fusion"
        prob_group = "prob_fusion"
        score_policy = "score_fusion"
        prob_policy = "prob_fusion"
        score_method = "Score Fusion"
        prob_method = "Prob Fusion"

    run_score = _find_latest_run(base / score_group)
    run_prob = _find_latest_run(base / prob_group)

    # Alignment checks (best-effort, warn via comments in output).
    cfg_score = _read_cfg(run_score)
    cfg_prob = _read_cfg(run_prob)
    keys = ["dataset", "delay_s"]
    for k in keys:
        vb = cfg_base.get(k, None)
        vs = cfg_score.get(k, None)
        vp = cfg_prob.get(k, None)
        if vb != vs or vb != vp:
            print(f"Warning: config mismatch for {k}: baselines={vb} score={vs} prob={vp}")

    # Select policies from the baselines run (single summary.csv).
    rows: list[PolicyRow] = []
    rows.append(
        _as_row(
            _select_one(summary_base, "planner_oracle"),
            method="Oracle Planner",
            policy="planner_oracle",
        )
    )
    rows.append(
        _as_row(
            _select_one(summary_base, "local_only"), method="Corrupted Planner", policy="local_only"
        )
    )
    rows.append(
        _as_row(_select_one(summary_base, "vlm_hold"), method="VLM Hold", policy="vlm_hold")
    )
    rows.append(
        _as_row(_select_one(summary_base, "vlm_stream"), method="VLM Stream", policy="vlm_stream")
    )

    rows_score = _read_summary_rows(run_score)
    rows_prob = _read_summary_rows(run_prob)
    rows.append(
        _as_row(_select_one(rows_score, score_policy), method=score_method, policy=score_policy)
    )
    rows.append(
        _as_row(_select_one(rows_prob, prob_policy), method=prob_method, policy=prob_policy)
    )

    n_tasks = None
    try:
        n_tasks = int(cfg_base.get("tasks", {}).get("tasks_built", 0)) or None
    except Exception:
        n_tasks = None

    tex = _render_latex_table(
        rows, delay_s=float(args.delay_s), n_tasks=n_tasks, label="tab:appendix_closed_loop_delay2"
    )
    out_p = Path(args.out_tex).expanduser().resolve()
    out_p.parent.mkdir(parents=True, exist_ok=True)
    out_p.write_text(tex, encoding="utf-8")
    print(f"Wrote: {out_p}")
    print(f"Baselines: {run_baselines}")
    print(f"Score    : {run_score}")
    print(f"Prob     : {run_prob}")


if __name__ == "__main__":
    main()
